repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/mwouts/jupytext
    rev: v1.16.1
    hooks:
    -   id: jupytext
        args: ["--sync"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy

- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint

- repo: https://github.com/jendrikseipp/vulture
  rev: v2.10
  hooks:
  - id: vulture

- repo: https://github.com/myint/autoflake
  rev: v2.3.0  # Remplacez v0.15.0 par la version souhaitée
  hooks:
  - id: autoflake
    args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "."]
